# Generated by Django 2.2 on 2019-06-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
            options={
                'db_table': 'coords',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_index', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('has_pbp', models.BooleanField(default=False)),
                ('msg_type', models.IntegerField(null=True)),
                ('msg_action_type', models.IntegerField(null=True)),
                ('period_from_pbp', models.IntegerField(null=True)),
                ('wc_timestring', models.CharField(max_length=32, null=True)),
                ('pc_timestring', models.CharField(max_length=32, null=True)),
                ('home_desc', models.CharField(max_length=256, null=True)),
                ('neutral_desc', models.CharField(max_length=256, null=True)),
                ('visitor_desc', models.CharField(max_length=256, null=True)),
                ('home_score', models.IntegerField(null=True)),
                ('visitor_score', models.IntegerField(null=True)),
                ('person1_type', models.IntegerField(null=True)),
                ('person2_type', models.IntegerField(null=True)),
                ('person3_type', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
                ('primary_color', models.CharField(max_length=32, null=True)),
                ('secondary_color', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.CharField(default='', max_length=8)),
                ('position', models.CharField(max_length=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbad3.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nbad3.Team')),
            ],
            options={
                'db_table': 'player_status',
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_timestamp', models.DateTimeField()),
                ('game_clock', models.DurationField()),
                ('shot_clock', models.DurationField(null=True)),
                ('coords', models.ManyToManyField(to='nbad3.Coords')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbad3.Event')),
            ],
            options={
                'db_table': 'moment',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_rel', to='nbad3.Team')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_rel', to='nbad3.Team')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbad3.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='nbad3.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='player1_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1_team', to='nbad3.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='nbad3.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='player2_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2_team', to='nbad3.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='nbad3.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='player3_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3_team', to='nbad3.Team'),
        ),
        migrations.AddField(
            model_name='coords',
            name='player_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbad3.PlayerStatus'),
        ),
    ]
